services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: projects
    volumes:
      - ./data:/data/db

  projects_service:
    image: oldrick/projects  # Replace with your Spring Boot Docker image
    depends_on:
      - mongodb
      - rabbitmq  # Ensure RabbitMQ starts before the projects_service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:password@mongodb:27017/projects?authSource=admin
      - SPRING_RABBITMQ_HOST=rabbitmq  # RabbitMQ service hostname in the container network
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    ports:
      - "8091:8080"  # Expose the service on port 8091
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"        # RabbitMQ default port for client connections
      - "15672:15672"      # RabbitMQ Management UI (optional)
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
