apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-unit
        image: oldrick/tca-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: tca
spec:
  type: LoadBalancer 
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: frontend

