apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tca-ingress
  namespace: tca 
spec:
  rules:
  - host: tca.com
    http:
      paths:
      - path: /api/project
        pathType: Prefix
        backend:
          service:
            name: projects
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend 
            port:
              number: 8080
---

