apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects
  namespace: tca
  labels:
    app: projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projects 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: projects
    spec:
      containers:
        - name: projects
          image: oldrick/projects
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: projects
  namespace: tca
spec: 
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: projects
---

