apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects
  labels:
    app: projects

spec:
  replicas: 2
  selector:
    matchLabels:
      app: projects 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: projects
    spec:
      containers:
        - name: projects
          image: oldrick/projects
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: projects-configmap
            - secretRef:
                name: projects-secret
