apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: tca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

# Deployment definition for MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: tca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.4
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: projects 
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db   # MongoDB's default data storage path
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc

---
# Service definition to expose MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: tca
spec:
  ports:
  - port: 27017
  selector:
    app: mongo
   
