spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: projects-service
          uri: ${URI_PROJECTS_SERVICE}
          predicates:
            - Path=/projects/**
          filters:
            - SetPath=/api/project

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

server:
  port: ${SERVER_PORT:8080}
