version: '3'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: projects
    volumes:
      - ./data:/data/db

  projects_service:
    image: oldrick/projects
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:password@mongodb:27017/projects?authSource=admin
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge


