
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: tca  # Specify the namespace here
  labels:
    app: api-gateway
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: oldrick/api-gateway:latest  # Replace with your image name and tag
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "default"  # Set to your active profile if needed
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: tca  # Specify the namespace here
  labels:
    app: api-gateway
spec:
  type: LoadBalancer  # Change to NodePort if you prefer
  ports:
  - port: 80         # Port that the service will expose
    targetPort: 8080  # Port that the container listens on
  selector:
    app: api-gateway
